# Generated by Django 3.2.9 on 2022-03-02 01:34

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('content', djongo.models.fields.EmbeddedField(model_container=api.models.BlogContent)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('content', djongo.models.fields.ArrayField(model_container=api.models.BlogContent)),
            ],
        ),
    ]
